code --install-extension adelonzeta.vscode-inky-snippets
code --install-extension aki77.rails-partial
code --install-extension aki77.rails-routes
code --install-extension Alan.stylus
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension chenxsan.vscode-standardjs
code --install-extension cssho.vscode-svgviewer
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension jemmyw.rails-fast-nav
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension misogi.ruby-rubocop
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension rafamel.subtle-brackets
code --install-extension rebornix.ruby
code --install-extension repeale.material-monokai
code --install-extension robinbentley.sass-indented
code --install-extension shanehofstetter.rails-open-partial
code --install-extension shinnn.stylelint
code --install-extension sianglim.slim
code --install-extension SimonSiefke.svg-preview
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sysoev.language-stylus
code --install-extension vincaslt.highlight-matching-tag
code --install-extension wingrunr21.vscode-ruby
code --install-extension ybaumes.highlight-trailing-white-spaces
